class _BotCommands:
    def __init__(self):
        self.StartCommand = 'startik'
        self.MirrorCommand = 'mirrorik'
        self.UnzipMirrorCommand = 'unzipik'
        self.TarMirrorCommand = 'tarik'
        self.ZipMirrorCommand = 'zipik'
        self.CancelMirror = 'cancelik'
        self.CancelAllCommand = 'cnlallik'
        self.ListCommand = 'listik'
        self.StatusCommand = 'statusik'
        self.AuthorizedUsersCommand = 'usersik'
        self.AuthorizeCommand = 'authik'
        self.UnAuthorizeCommand = 'unauthik'
        self.AddSudoCommand = 'addsudoik'
        self.RmSudoCommand = 'rmsudoik'
        self.PingCommand = 'pingik'
        self.RestartCommand = 'restartik'
        self.StatsCommand = 'statik'
        self.HelpCommand = 'hlpik'
        self.LogCommand = 'logik'
        self.SpeedCommand = 'speedtestik'
        self.CloneCommand = 'cloneik'
        self.CountCommand = 'count'
        self.WatchCommand = 'watch'
        self.TarWatchCommand = 'tarwatch'
        self.DeleteCommand = 'del'
        self.ConfigMenuCommand = 'config'
        self.ShellCommand = 'shell'
        self.UpdateCommand = 'updateik'
        self.ExecHelpCommand = 'exechelp'
        self.TsHelpCommand = 'tshelp'

BotCommands = _BotCommands()
